version: "3.7"

services:
  tfjsremix-v1:
    container_name: tfjsremix-v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
